/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 14
 */
export type EventDetailEventType =
  (typeof EventDetailEventType)[keyof typeof EventDetailEventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventDetailEventType = {
  CONFERENCE: "CONFERENCE",
  SINGLE_SESSION: "SINGLE_SESSION",
} as const;
