/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export interface EventBranding {
  primary_color?: string;
  secondary_color?: string;
  /** @nullable */
  logo_url?: string | null;
  /** @nullable */
  banner_url?: string | null;
}
