/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export interface EventBase3 {
  id?: number;
  title: string;
  start_date: string;
  end_date: string;
}
