/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 9
 */
export type EventUserDetailRole =
  (typeof EventUserDetailRole)[keyof typeof EventUserDetailRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventUserDetailRole = {
  ADMIN: "ADMIN",
  ORGANIZER: "ORGANIZER",
  MODERATOR: "MODERATOR",
  SPEAKER: "SPEAKER",
  ATTENDEE: "ATTENDEE",
} as const;
