/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 9
 */
export type EventDetailStatus =
  (typeof EventDetailStatus)[keyof typeof EventDetailStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventDetailStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;
