/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { EventUpdateEventType } from "./eventUpdateEventType";
import type { EventUpdateStatus } from "./eventUpdateStatus";
import type { EventUpdateBranding } from "./eventUpdateBranding";

export interface EventUpdate {
  title?: string;
  description?: string;
  event_type?: EventUpdateEventType;
  start_date?: string;
  end_date?: string;
  company_name?: string;
  status?: EventUpdateStatus;
  branding?: EventUpdateBranding;
}
