/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { EventCreateEventType } from "./eventCreateEventType";
import type { EventCreateStatus } from "./eventCreateStatus";
import type { EventCreateBranding } from "./eventCreateBranding";

export interface EventCreate {
  title: string;
  event_type: EventCreateEventType;
  start_date: string;
  end_date: string;
  company_name: string;
  description?: string;
  status?: EventCreateStatus;
  branding?: EventCreateBranding;
}
