/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type EventCreateStatus =
  (typeof EventCreateStatus)[keyof typeof EventCreateStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventCreateStatus = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;
