/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type EventUserCreateRole =
  (typeof EventUserCreateRole)[keyof typeof EventUserCreateRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventUserCreateRole = {
  ADMIN: "ADMIN",
  ORGANIZER: "ORGANIZER",
  MODERATOR: "MODERATOR",
  SPEAKER: "SPEAKER",
  ATTENDEE: "ATTENDEE",
} as const;
