/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export interface EventSpeakerInfoUpdate {
  speaker_bio?: string;
  speaker_title?: string;
}
