/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { EventBase1Status } from "./eventBase1Status";

export interface EventBase1 {
  id?: number;
  title: string;
  start_date: string;
  /** @maxLength 9 */
  status?: EventBase1Status;
}
