/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 9
 */
export type EventBase1Status =
  (typeof EventBase1Status)[keyof typeof EventBase1Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventBase1Status = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;
