/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { EventUserDetailRole } from "./eventUserDetailRole";
import type { EventBase2 } from "./eventBase2";
import type { UserBase3 } from "./userBase3";

export interface EventUserDetail {
  readonly user_name?: string;
  readonly is_speaker?: boolean;
  readonly is_organizer?: boolean;
  event_id: number;
  user_id: number;
  /** @maxLength 9 */
  role: EventUserDetailRole;
  /** @nullable */
  speaker_bio?: string | null;
  /** @nullable */
  speaker_title?: string | null;
  /** @nullable */
  created_at?: string | null;
  readonly event?: EventBase2;
  readonly user?: UserBase3;
}
