/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiEventsEventIdSessionsParams = {
  /**
   * Filter by day number
   */
  day_number?: number;
  /**
   * Page number (default: 1)
   */
  page?: number;
  /**
   * Items per page (default: 50)
   */
  per_page?: number;
};
