/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationBase } from "./organizationBase";

export type GetApiOrganizations200 = {
  total_items?: number;
  total_pages?: number;
  current_page?: number;
  per_page?: number;
  self?: string;
  first?: string;
  last?: string;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  prev?: string | null;
  organizations?: OrganizationBase[];
};
