/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type OrganizationUserCreateRole =
  (typeof OrganizationUserCreateRole)[keyof typeof OrganizationUserCreateRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationUserCreateRole = {
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  OWNER: "OWNER",
} as const;
