/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { UserBase } from "./userBase";
import type { EventBase1 } from "./eventBase1";

export interface OrganizationDetail {
  owners?: UserBase[];
  id?: number;
  name: string;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  readonly member_count?: number;
  readonly owner_count?: number;
  readonly upcoming_events?: readonly EventBase1[];
}
