/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 6
 */
export type OrganizationUserDetailRole =
  (typeof OrganizationUserDetailRole)[keyof typeof OrganizationUserDetailRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationUserDetailRole = {
  ADMIN: "ADMIN",
  MEMBER: "MEMBER",
  OWNER: "OWNER",
} as const;
