/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaMeta2Role } from "./schemaMeta2Role";

export interface SchemaMeta2 {
  user_id: number;
  role: SchemaMeta2Role;
  order?: number;
}
