/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type SchemaMeta2Role =
  (typeof SchemaMeta2Role)[keyof typeof SchemaMeta2Role];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SchemaMeta2Role = {
  HOST: "HOST",
  SPEAKER: "SPEAKER",
  PANELIST: "PANELIST",
  MODERATOR: "MODERATOR",
  KEYNOTE: "KEYNOTE",
} as const;
