/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaMeta3Role } from "./schemaMeta3Role";

export interface SchemaMeta3 {
  role?: SchemaMeta3Role;
  order?: number;
}
