/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 12
 */
export type SessionBase1SessionType =
  (typeof SessionBase1SessionType)[keyof typeof SessionBase1SessionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionBase1SessionType = {
  KEYNOTE: "KEYNOTE",
  WORKSHOP: "WORKSHOP",
  PANEL: "PANEL",
  PRESENTATION: "PRESENTATION",
  NETWORKING: "NETWORKING",
  QA: "QA",
} as const;
