/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionSpeakerDetailSchemaSocialLinks } from "./sessionSpeakerDetailSchemaSocialLinks";
import type { SessionSpeakerDetailSchemaRole } from "./sessionSpeakerDetailSchemaRole";
import type { SessionBase2 } from "./sessionBase2";
import type { UserBase4 } from "./userBase4";

export interface SessionSpeakerDetailSchema {
  readonly speaker_name?: string;
  image_url?: string;
  title?: string;
  company_name?: string;
  social_links?: SessionSpeakerDetailSchemaSocialLinks;
  session_id: number;
  user_id: number;
  /** @maxLength 9 */
  role: SessionSpeakerDetailSchemaRole;
  /** @nullable */
  order?: number | null;
  /** @nullable */
  created_at?: string | null;
  readonly session?: SessionBase2;
  readonly user?: UserBase4;
}
