/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type SessionUpdateSessionType =
  (typeof SessionUpdateSessionType)[keyof typeof SessionUpdateSessionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionUpdateSessionType = {
  KEYNOTE: "KEYNOTE",
  WORKSHOP: "WORKSHOP",
  PANEL: "PANEL",
  PRESENTATION: "PRESENTATION",
  NETWORKING: "NETWORKING",
  QA: "QA",
} as const;
