/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionCreateSessionType } from "./sessionCreateSessionType";
import type { SessionCreateStatus } from "./sessionCreateStatus";

export interface SessionCreate {
  title: string;
  session_type: SessionCreateSessionType;
  status?: SessionCreateStatus;
  description?: string;
  start_time: string;
  end_time: string;
  stream_url?: string;
  day_number: number;
}
