/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionSpeakerSchemaSocialLinks } from "./sessionSpeakerSchemaSocialLinks";
import type { SessionSpeakerSchemaRole } from "./sessionSpeakerSchemaRole";

export interface SessionSpeakerSchema {
  readonly speaker_name?: string;
  image_url?: string;
  title?: string;
  company_name?: string;
  social_links?: SessionSpeakerSchemaSocialLinks;
  session_id: number;
  user_id: number;
  /** @maxLength 9 */
  role: SessionSpeakerSchemaRole;
  /** @nullable */
  order?: number | null;
  /** @nullable */
  created_at?: string | null;
}
