/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionDetailStatus } from "./sessionDetailStatus";
import type { SessionDetailSessionType } from "./sessionDetailSessionType";
import type { EventBase3 } from "./eventBase3";

export interface SessionDetail {
  readonly duration_minutes?: number;
  readonly formatted_duration?: string;
  readonly is_live?: boolean;
  readonly is_completed?: boolean;
  readonly is_cancelled?: boolean;
  readonly is_upcoming?: boolean;
  readonly is_in_progress?: boolean;
  id?: number;
  event_id: number;
  /** @maxLength 13 */
  status: SessionDetailStatus;
  /** @maxLength 12 */
  session_type: SessionDetailSessionType;
  title: string;
  /** @nullable */
  description?: string | null;
  start_time: string;
  end_time: string;
  /** @nullable */
  stream_url?: string | null;
  day_number: number;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  readonly event?: EventBase3;
}
