/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export type SessionCreateStatus =
  (typeof SessionCreateStatus)[keyof typeof SessionCreateStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionCreateStatus = {
  SCHEDULED: "SCHEDULED",
  STARTING_SOON: "STARTING_SOON",
  LIVE: "LIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;
