/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @maxLength 9
 */
export type SessionSpeakerDetailSchemaRole =
  (typeof SessionSpeakerDetailSchemaRole)[keyof typeof SessionSpeakerDetailSchemaRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionSpeakerDetailSchemaRole = {
  HOST: "HOST",
  SPEAKER: "SPEAKER",
  PANELIST: "PANELIST",
  MODERATOR: "MODERATOR",
  KEYNOTE: "KEYNOTE",
} as const;
