/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionBase1SessionType } from "./sessionBase1SessionType";

export interface SessionBase1 {
  id?: number;
  title: string;
  start_time: string;
  end_time: string;
  /** @maxLength 12 */
  session_type: SessionBase1SessionType;
  /** @nullable */
  description?: string | null;
}
