/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SessionUpdateSessionType } from "./sessionUpdateSessionType";
import type { SessionUpdateStatus } from "./sessionUpdateStatus";

export interface SessionUpdate {
  title?: string;
  session_type?: SessionUpdateSessionType;
  status?: SessionUpdateStatus;
  description?: string;
  start_time?: string;
  end_time?: string;
  stream_url?: string;
  day_number?: number;
}
