/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { SchemaMeta } from "./schemaMeta";

/**
 * Unprocessable Content
 */
export type UnprocessableContentResponse = SchemaMeta;
