/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */

export interface UserBase2 {
  id?: number;
  readonly full_name?: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  company_name?: string | null;
}
