/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationBase } from "./organizationBase";
import type { EventBase } from "./eventBase";
import type { SessionBase } from "./sessionBase";

export interface UserDetail {
  readonly full_name?: string;
  id?: number;
  email: string;
  first_name: string;
  last_name: string;
  /** @nullable */
  company_name?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  image_url?: string | null;
  social_links?: unknown;
  is_active?: boolean;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
  organizations?: OrganizationBase[];
  events?: EventBase[];
  speaking_sessions?: SessionBase[];
}
