/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Atria API
 * OpenAPI spec version: 1.0.0
 */
import type { UserUpdateSocialLinks } from "./userUpdateSocialLinks";

export interface UserUpdate {
  first_name?: string;
  last_name?: string;
  company_name?: string;
  title?: string;
  bio?: string;
  image_url?: string;
  social_links?: UserUpdateSocialLinks;
}
