"""Add soft delete fields to events table

Revision ID: 118120f66269
Revises: f5a3932810c6
Create Date: 2025-08-12 18:14:21.436863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118120f66269'
down_revision = 'f5a3932810c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
