"""Add REMOVED status to ConnectionStatus enum

Revision ID: 2713aaed8111
Revises: 8e3e54a7a3bb
Create Date: 2025-08-28 01:44:58.842093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2713aaed8111'
down_revision = '8e3e54a7a3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add REMOVED to the connectionstatus enum (uppercase to match other enum values)
    op.execute("ALTER TYPE connectionstatus ADD VALUE IF NOT EXISTS 'REMOVED'")
    
    with op.batch_alter_table('direct_message_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dm_threads_user1_cutoff_last_msg'), postgresql_where='(user1_cutoff IS NOT NULL)')
        batch_op.drop_index(batch_op.f('idx_dm_threads_user2_cutoff_last_msg'), postgresql_where='(user2_cutoff IS NOT NULL)')

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dm_messages_thread_created'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dm_messages_thread_created'), ['thread_id', 'created_at'], unique=False)

    with op.batch_alter_table('direct_message_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dm_threads_user2_cutoff_last_msg'), ['user2_id', 'user2_cutoff', 'last_message_at'], unique=False, postgresql_where='(user2_cutoff IS NOT NULL)')
        batch_op.create_index(batch_op.f('idx_dm_threads_user1_cutoff_last_msg'), ['user1_id', 'user1_cutoff', 'last_message_at'], unique=False, postgresql_where='(user1_cutoff IS NOT NULL)')

    # ### end Alembic commands ###
