"""Add performance indexes for agenda queries

Revision ID: 66e463f92dd2
Revises: 2713aaed8111
Create Date: 2025-09-02 02:13:19.541578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e463f92dd2'
down_revision = '2713aaed8111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.create_index('idx_event_users_user_event', ['user_id', 'event_id'], unique=False)

    with op.batch_alter_table('session_speakers', schema=None) as batch_op:
        batch_op.create_index('idx_session_speakers_session_order', ['session_id', 'order'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_event_day_time', ['event_id', 'day_number', 'start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_sessions_event_day_time')

    with op.batch_alter_table('session_speakers', schema=None) as batch_op:
        batch_op.drop_index('idx_session_speakers_session_order')

    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_index('idx_event_users_user_event')

    # ### end Alembic commands ###
