"""Add indexes for networking page performance and fix N+1 query

Revision ID: 66e7b507779d
Revises: 66e463f92dd2
Create Date: 2025-09-02 03:23:24.854200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e7b507779d'
down_revision = '66e463f92dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index('idx_connections_recipient_requester', ['recipient_id', 'requester_id'], unique=False)
        batch_op.create_index('idx_connections_recipient_status_created', ['recipient_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.create_index('idx_event_users_event_banned_role', ['event_id', 'is_banned', 'role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_index('idx_event_users_event_banned_role')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index('idx_connections_recipient_status_created')
        batch_op.drop_index('idx_connections_recipient_requester')

    # ### end Alembic commands ###
