"""Add IN_PERSON to EventFormat enum

Revision ID: 67b73d57262a
Revises: 41ee1eccb261
Create Date: 2025-07-20 19:53:15.170455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b73d57262a'
down_revision = '41ee1eccb261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
