"""Add display_order to chat_rooms

Revision ID: 718866fb463c
Revises: 67b73d57262a
Create Date: 2025-07-25 01:27:04.768529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718866fb463c'
down_revision = '67b73d57262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Float(), nullable=True))
    
    # Set initial display_order values - start at 10 and increment by 10 within each type
    # This gives us room to reorder items between existing ones
    op.execute("""
        WITH numbered_rooms AS (
            SELECT id, 
                   ROW_NUMBER() OVER (PARTITION BY event_id, room_type ORDER BY name) * 10.0 as new_order
            FROM chat_rooms
        )
        UPDATE chat_rooms 
        SET display_order = numbered_rooms.new_order
        FROM numbered_rooms
        WHERE chat_rooms.id = numbered_rooms.id
    """)
    
    # Now make the column non-nullable
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.alter_column('display_order', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
