"""add Mux BYOA credentials to organizations

Revision ID: 72e8864b68e5
Revises: d8f2d07ddea9
Create Date: 2025-10-28 23:33:09.965628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e8864b68e5'
down_revision = 'd8f2d07ddea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mux_token_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mux_token_secret', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mux_signing_key_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mux_signing_private_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('mux_signing_private_key')
        batch_op.drop_column('mux_signing_key_id')
        batch_op.drop_column('mux_token_secret')
        batch_op.drop_column('mux_token_id')

    # ### end Alembic commands ###
