"""Add GREEN_ROOM chat type and session chat_mode

Revision ID: 786370c454f1
Revises: 7b15b01c6f88
Create Date: 2025-07-14 19:11:58.524431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786370c454f1'
down_revision = '7b15b01c6f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update ChatRoomType enum to add GREEN_ROOM (uppercase to match existing values)
    op.execute("ALTER TYPE chatroomtype ADD VALUE IF NOT EXISTS 'GREEN_ROOM'")
    
    # Commit the enum change so it can be used
    op.execute("COMMIT")
    
    # Update the check constraint to include GREEN_ROOM in a new transaction
    op.execute("BEGIN")
    op.drop_constraint('chat_room_type_session_check', 'chat_rooms', type_='check')
    op.create_check_constraint(
        'chat_room_type_session_check',
        'chat_rooms',
        "(room_type IN ('GLOBAL', 'ADMIN', 'GREEN_ROOM') AND session_id IS NULL) OR "
        "(room_type IN ('PUBLIC', 'BACKSTAGE') AND session_id IS NOT NULL)"
    )
    
    # Create SessionChatMode enum
    sessionchatmode = sa.Enum('ENABLED', 'BACKSTAGE_ONLY', 'DISABLED', name='sessionchatmode')
    sessionchatmode.create(op.get_bind())
    
    # Add chat_mode column to sessions with default value
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_mode', sessionchatmode, nullable=False, server_default='ENABLED'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove chat_mode column from sessions
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('chat_mode')
    
    # Drop SessionChatMode enum
    sessionchatmode = sa.Enum('ENABLED', 'BACKSTAGE_ONLY', 'DISABLED', name='sessionchatmode')
    sessionchatmode.drop(op.get_bind())
    
    # Note: We can't remove GREEN_ROOM from the enum as PostgreSQL doesn't support it

    # ### end Alembic commands ###
