"""Add session chat rooms with room_type enum

Revision ID: 7b15b01c6f88
Revises: 37eec564a2db
Create Date: 2025-07-11 23:45:07.059883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b15b01c6f88'
down_revision = '37eec564a2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type
    chatroomtype = sa.Enum('GLOBAL', 'PUBLIC', 'BACKSTAGE', 'ADMIN', name='chatroomtype')
    chatroomtype.create(op.get_bind())
    
    # Add new columns
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.Enum('GLOBAL', 'PUBLIC', 'BACKSTAGE', 'ADMIN', name='chatroomtype'), nullable=False))
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.create_foreign_key('fk_chat_rooms_session_id', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('unique_session_room_type', ['session_id', 'room_type'])
    
    # Add check constraint
    op.create_check_constraint(
        'chat_room_type_session_check',
        'chat_rooms',
        "(room_type IN ('GLOBAL', 'ADMIN') AND session_id IS NULL) OR "
        "(room_type IN ('PUBLIC', 'BACKSTAGE') AND session_id IS NOT NULL)"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraint first
    op.drop_constraint('chat_room_type_session_check', 'chat_rooms', type_='check')
    
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_rooms_session_id', type_='foreignkey')
        batch_op.drop_constraint('unique_session_room_type', type_='unique')
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('room_type')
        batch_op.drop_column('session_id')
    
    # Drop the enum type
    chatroomtype = sa.Enum('GLOBAL', 'PUBLIC', 'BACKSTAGE', 'ADMIN', name='chatroomtype')
    chatroomtype.drop(op.get_bind())

    # ### end Alembic commands ###