"""Add soft delete fields to ChatMessage

Revision ID: 9abed782819f
Revises: fa31a7e10fa4
Create Date: 2025-08-01 23:33:50.028023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abed782819f'
down_revision = 'fa31a7e10fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
