"""Add privacy settings and moderation fields

Revision ID: privacy_moderation_001
Revises: fa31a7e10fa4
Create Date: 2025-01-08 18:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'privacy_moderation_001'
down_revision = '8ffc625fa02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add privacy_settings to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_settings', sa.JSON(), nullable=False, server_default='{}'))
    
    # Update default privacy settings for existing users
    op.execute("""
        UPDATE users 
        SET privacy_settings = '{
            "email_visibility": "connections_organizers",
            "show_public_email": false,
            "public_email": null,
            "allow_connection_requests": "everyone",
            "show_social_links": "everyone",
            "show_company": true,
            "show_bio": true
        }'
    """)
    
    # Add moderation fields to event_users table
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_overrides', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('banned_by', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_chat_banned', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('chat_ban_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('chat_ban_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('moderation_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            'event_users_banned_by_fkey', 
            'users', 
            ['banned_by'], 
            ['id'],
            ondelete='SET NULL'
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from event_users
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_constraint('event_users_banned_by_fkey', type_='foreignkey')
        batch_op.drop_column('moderation_notes')
        batch_op.drop_column('chat_ban_reason')
        batch_op.drop_column('chat_ban_until')
        batch_op.drop_column('is_chat_banned')
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('banned_by')
        batch_op.drop_column('banned_at')
        batch_op.drop_column('is_banned')
        batch_op.drop_column('privacy_overrides')
    
    # Remove column from users
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('privacy_settings')
    
    # ### end Alembic commands ###