"""add jitsi and other streaming platforms

Revision ID: d52998f34f7e
Revises: 72e8864b68e5
Create Date: 2025-11-23 03:35:52.996749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52998f34f7e'
down_revision = '72e8864b68e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jaas_app_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jaas_api_key_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('jaas_private_key_encrypted', sa.Text(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jitsi_room_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # Drop existing CHECK constraint and recreate with new platforms (JITSI, OTHER)
    op.drop_constraint('valid_streaming_platform', 'sessions', type_='check')
    op.create_check_constraint(
        'valid_streaming_platform',
        'sessions',
        "streaming_platform IN ('VIMEO', 'MUX', 'ZOOM', 'JITSI', 'OTHER') OR streaming_platform IS NULL"
    )


def downgrade():
    # Restore original CHECK constraint (before JITSI and OTHER were added)
    op.drop_constraint('valid_streaming_platform', 'sessions', type_='check')
    op.create_check_constraint(
        'valid_streaming_platform',
        'sessions',
        "streaming_platform IN ('VIMEO', 'MUX', 'ZOOM') OR streaming_platform IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('jitsi_room_name')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('jaas_private_key_encrypted')
        batch_op.drop_column('jaas_api_key_encrypted')
        batch_op.drop_column('jaas_app_id')

    # ### end Alembic commands ###
