"""add streaming platform fields to sessions

Revision ID: d8f2d07ddea9
Revises: e51b275a36cf
Create Date: 2025-10-28 23:13:19.936951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f2d07ddea9'
down_revision = 'e51b275a36cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streaming_platform', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('zoom_meeting_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zoom_passcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mux_playback_policy', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###

    # Add CHECK constraint for streaming_platform enum-like validation
    op.create_check_constraint(
        'valid_streaming_platform',
        'sessions',
        "streaming_platform IN ('VIMEO', 'MUX', 'ZOOM') OR streaming_platform IS NULL"
    )

    # Backfill existing sessions: set streaming_platform to VIMEO if stream_url exists
    # This assumes existing sessions are using Vimeo (current implementation)
    op.execute("""
        UPDATE sessions
        SET streaming_platform = 'VIMEO'
        WHERE stream_url IS NOT NULL AND streaming_platform IS NULL;
    """)


def downgrade():
    # Drop CHECK constraint before dropping columns
    op.drop_constraint('valid_streaming_platform', 'sessions', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('mux_playback_policy')
        batch_op.drop_column('zoom_passcode')
        batch_op.drop_column('zoom_meeting_id')
        batch_op.drop_column('streaming_platform')

    # ### end Alembic commands ###
