"""Add session visibility window and VOD fields

Revision ID: dc1baaa74127
Revises: d52998f34f7e
Create Date: 2025-12-28 20:18:26.265799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1baaa74127'
down_revision = 'd52998f34f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_visibility_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility_minutes_override', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vod_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vod_platform', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('vod_platform')
        batch_op.drop_column('vod_url')
        batch_op.drop_column('visibility_minutes_override')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('session_visibility_minutes')

    # ### end Alembic commands ###
