"""Add organization_invitations table

Revision ID: e11ba2805ba3
Revises: 718866fb463c
Create Date: 2025-07-29 22:13:45.089785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e11ba2805ba3'
down_revision = '718866fb463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', 'OWNER', name='organizationuserrole', create_type=False), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'DECLINED', 'CANCELLED', name='invitationstatus', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('invited_by_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.create_index('idx_org_email', ['organization_id', 'email'], unique=False)
        batch_op.create_index('idx_org_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_invitations_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_organization_invitations_email'))
        batch_op.drop_index('idx_org_status')
        batch_op.drop_index('idx_org_expires_at')
        batch_op.drop_index('idx_org_email')

    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
