"""Add main_session_id to Event model for single session navigation

Revision ID: eee0ea388710
Revises: 66e7b507779d
Create Date: 2025-09-11 19:23:44.485465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee0ea388710'
down_revision = '66e7b507779d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_session_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'sessions', ['main_session_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('main_session_id')

    # ### end Alembic commands ###
