"""Update privacy settings enums - remove everyone option

Revision ID: f5a3932810c6
Revises: privacy_moderation_001
Create Date: 2025-08-09 08:56:51.765913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a3932810c6'
down_revision = 'privacy_moderation_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_users_banned_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['banned_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_users_banned_by_fkey'), 'users', ['banned_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
