"""add stream_mode show_video show_recording to sessions

Revision ID: f8b14398a991
Revises: dc1baaa74127
Create Date: 2025-12-30 06:56:55.319502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b14398a991'
down_revision = 'dc1baaa74127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        # stream_mode: NULL = backward compat (infer from streaming_platform)
        batch_op.add_column(sa.Column('stream_mode', sa.String(length=10), nullable=True))
        # show_video: default True (existing sessions should remain visible)
        batch_op.add_column(sa.Column('show_video', sa.Boolean(), nullable=False, server_default='true'))
        # show_recording: default True (existing sessions with VOD should show it)
        batch_op.add_column(sa.Column('show_recording', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('show_recording')
        batch_op.drop_column('show_video')
        batch_op.drop_column('stream_mode')

    # ### end Alembic commands ###
