"""fix unique constraint for event scoped threads

Revision ID: f96e4714ccd7
Revises: a1b2c3d4e5f6
Create Date: 2025-08-16 01:50:02.791353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96e4714ccd7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_dm_threads_event_scope'))
        batch_op.drop_index(batch_op.f('idx_dm_threads_user1_cutoff'))
        batch_op.drop_index(batch_op.f('idx_dm_threads_user2_cutoff'))

    # Fix the unique constraint to include event_scope_id
    # Drop the old constraint that only considers (user1_id, user2_id)
    op.drop_constraint('uix_dm_thread_users', 'direct_message_threads', type_='unique')
    
    # Create new constraint that includes event_scope_id
    # This allows: one global thread + one thread per event between same users
    # PostgreSQL treats NULLs as distinct, so this works correctly
    op.create_unique_constraint(
        'uix_dm_thread_users_scope', 
        'direct_message_threads', 
        ['user1_id', 'user2_id', 'event_scope_id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore the old constraint
    op.drop_constraint('uix_dm_thread_users_scope', 'direct_message_threads', type_='unique')
    op.create_unique_constraint('uix_dm_thread_users', 'direct_message_threads', ['user1_id', 'user2_id'])
    
    with op.batch_alter_table('direct_message_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_dm_threads_user2_cutoff'), ['user2_id', 'user2_cutoff'], unique=False)
        batch_op.create_index(batch_op.f('idx_dm_threads_user1_cutoff'), ['user1_id', 'user1_cutoff'], unique=False)
        batch_op.create_index(batch_op.f('idx_dm_threads_event_scope'), ['event_scope_id'], unique=False)

    # ### end Alembic commands ###
