"""Add email verification and password reset models

Revision ID: fa31a7e10fa4
Revises: e11ba2805ba3
Create Date: 2025-08-01 01:45:44.925547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa31a7e10fa4'
down_revision = 'e11ba2805ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_token_expires', ['token', 'expires_at'], unique=False)
        batch_op.create_index('idx_user_email', ['user_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verifications_token'), ['token'], unique=True)

    op.create_table('password_resets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index('idx_token_expires_used', ['token', 'expires_at', 'used_at'], unique=False)
        batch_op.create_index('idx_user_token', ['user_id', 'token'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=True)

    # Add column with a default value for existing rows
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='true'))
    
    # Set all existing users as verified (they were created before email verification was required)
    op.execute("UPDATE users SET email_verified = true")
    
    # Remove the server default so new users must explicitly set this value
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))
        batch_op.drop_index(batch_op.f('ix_password_resets_email'))
        batch_op.drop_index('idx_user_token')
        batch_op.drop_index('idx_token_expires_used')

    op.drop_table('password_resets')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_token'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_email'))
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_token_expires')

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
